# Generated by Django 4.1.2 on 2022-11-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(help_text="Author of the article", max_length=50),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the article", max_length=100),
                ),
                ("content", models.TextField(help_text="Content of the article")),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(help_text="Full name", max_length=100)),
                ("author_uri", models.CharField(help_text="Full name", max_length=100)),
                (
                    "top_used_words",
                    models.JSONField(help_text="Top used words by author"),
                ),
            ],
        ),
    ]
