# Generated by Django 4.1.2 on 2022-11-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="author_uri",
            field=models.CharField(help_text="Full name", max_length=100),
        ),
        migrations.AlterField(
            model_name="author",
            name="full_name",
            field=models.CharField(help_text="Full name", max_length=100),
        ),
        migrations.AlterField(
            model_name="author",
            name="top_used_words",
            field=models.JSONField(help_text="Top used words by author"),
        ),
    ]
